### PR TITLE
Improved visibility of keyboard focus highlight

### PR DESCRIPTION
**Pull request by jakrams**

### CODE REVIEW

**Comment by jakrams** [comment]
Improved keyboard focus highlight for tabs:

image

**Comment by jakrams** [comment]
Buttons:

image

**Comment by jakrams** [comment]
Comboboxes:

image

**Comment by jakrams** [comment]
Active widgets:

image

**Review by FlorianBorn71 — APPROVED** [review]

**Review by MichaelZp0 — APPROVED** [review]

**Pull request merged**
